#!/bin/sh /etc/rc.common

START=99
STOP=10

boot() {
    # 1. Auto-bind interface Ethernet ke br-lan jika kosong/salah
    ETH_DEV=$(ip -o link show | awk -F': ' '$2 ~ /^(eth|enp|ens|eno)/ {print $2}' | head -n 1)
    [ -z "$ETH_DEV" ] && ETH_DEV=$(ip -o link show | awk -F': ' '$2 !~ /^(lo|br-|vir|wlan|docker)/ {print $2}' | head -n 1)
    
    if [ -n "$ETH_DEV" ]; then
        CURRENT_IFNAME=$(uci get network.lan.ifname 2>/dev/null)
        case "$CURRENT_IFNAME" in
            *"$ETH_DEV"*) ;;
            *)
                uci set network.lan.ifname="$ETH_DEV"
                uci commit network
                ifup lan
                ;;
        esac
    fi

    # 2. Paksa WiFi aktif, country ID, SSID Masta Gohim
    for dev in $(uci show wireless 2>/dev/null | grep "=wifi-device" | cut -d'.' -f2 | cut -d'=' -f1); do
        uci set wireless.${dev}.disabled='0'
        uci set wireless.${dev}.country='ID'
    done

    if ! uci show wireless 2>/dev/null | grep -q "Masta Gohim"; then
        uci set wireless.default_radio0=wifi-iface 2>/dev/null
        uci set wireless.default_radio0.device='radio0'
        uci set wireless.default_radio0.mode='ap'
        uci set wireless.default_radio0.ssid='Masta Gohim'
        uci set wireless.default_radio0.encryption='psk2'
        uci set wireless.default_radio0.key='12345678'

        uci set wireless.default_radio1=wifi-iface 2>/dev/null
        uci set wireless.default_radio1.device='radio1'
        uci set wireless.default_radio1.mode='ap'
        uci set wireless.default_radio1.ssid='Masta Gohim'
        uci set wireless.default_radio1.encryption='psk2'
        uci set wireless.default_radio1.key='12345678'
    fi
    uci commit wireless
    wifi up
}
